import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js Resource-Scheduling Calendar (Open-Source)",
  description: "Generated by DayPilot UI Builder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>

      <div className="header">
          <h1><a href='https://code.daypilot.org/13080/next-js-resource-scheduling-calendar-open-source'>Next.js Resource-Scheduling Calendar (Open-Source)</a></h1>
          <div><a href="https://javascript.daypilot.org/">DayPilot for JavaScript</a> - HTML5 Calendar/Scheduling Components for JavaScript/Angular/React/Vue</div>
      </div>
      <div className="main">
          {children}
          <div className="generated">Generated using <a href="https://builder.daypilot.org/">DayPilot UI Builder</a>.</div>
      </div>
      </body>
    </html>
);
}
