import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next.js Resource-Scheduling Calendar (Open-Source)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
      <div className="header">
          <h1><a href='https://code.daypilot.org/13080/next-js-resource-scheduling-calendar-open-source'>Next.js Resource-Scheduling Calendar (Open-Source)</a></h1>
          <div><a href="https://javascript.daypilot.org/">DayPilot for JavaScript</a> - HTML5 Calendar/Scheduling Components for JavaScript/Angular/React/Vue</div>
      </div>

      <div className="main">
          {children}
      </div>

      </body>
      </html>
  )
}
